site_name: Caldera Forms CiviCRM
repo_url: https://github.com/mecachisenros/caldera-forms-civicrm
theme: material
markdown_extensions:
pages:
- Introduction: index.md
- Overview: overview.md
- Procesors: processors.md
- Custom Fields: custom-fields.md
- Developer docs:
  - Contribute: dev/contribute.md
